#!/bin/bash

################ php lint #####################
# Run change set through php lint
git diff --name-status | awk '{ if ($1 != "D") print $2}' | grep -e \.php$  | xargs -n1 php -l | exit $?

################ phpcs #####################
# Run change set through phpcs (note: phpcs must be installed and your preferrred coding standards must be set as default)
log_path=/tmp/phpcs.log

git diff --name-status | awk '{ if ($1 != "D") print $2}' | grep -e \.php$  | xargs -n1 phpcs --standard=Symfony2 > $log_path

error_count=`cat $log_path | grep ERROR | wc -l`
warning_count=`cat $log_path | grep ERROR | wc -l`

echo ""
if [ $error_count -gt 1 ]
then
    error_count=$(($error_count-1))
    echo "Please fix the following ($error_count) errors and ($warning_count) warnings."
    cat $log_path
    exit 1;
else
    #echo 'Holy bug free code, Batman! :)';
    exit 0;
fi

