#!/bin/bash


# Trim trailing whitespace
echo ""
echo "Triming whitespace…"
git diff --name-status | awk '{ if ($1 != "D") print $2}' | xargs -n1 sed -i "s/[[:space:]]*$//"


# Run change set through php lint
echo ""
echo "Checking PHP syntax…"
lint_ok=0
git diff --name-status | awk '{ if ($1 != "D") print $2}' | grep -e \.php$  | xargs -n1 php -l
ret_val=$?

if [ $ret_val -ne 0 ]
then
    exit $ret_val
fi


# Run change set through phpcs (note: phpcs must be installed as well as the Symfony2 coding standard)
echo ""
echo "Checking Symfony2 coding standards…"
log_path=/tmp/phpcs_results.log

git diff --name-status | awk '{ if ($1 != "D") print $2}' | grep -e \.php$  | xargs -n1 phpcs --standard=Symfony2 > $log_path

error_count=`cat $log_path | grep ERROR | wc -l`
warning_count=`cat $log_path | grep WARNING | wc -l`

if [ $error_count -gt 1 ]
then
    error_count=$(($error_count-1))
    echo "Please fix the following ($error_count) errors and ($warning_count) warnings."
    cat $log_path
    exit 1;
else
    echo 'Holy bug free code, Batman! :)';
    unlink $log_path
    exit 0;
fi

